apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels:
    project: roboshop
    enivironment: dev
spec:
  containers:
  - name: almalinux
    image: almalinux:9
  - name: nginx
    image: nginx